### ISSUE TITLE
[ACCESS]

### ISSUE THREAD

**Issue by port19x** [possum64team/backend-admin-stuff#2]
Discord Name: Ura#8572 (Nick: pyssom)
Are you a web developer:N
Are you an app developer:N
Do you want to be added on gitlab (if yes whats your username there):N
How do you want to be listed on the TEAM.md file: pyssom <pyssom@possum64.com>]

What is your best possum fact or joke?
Some possums have a natural resistance to snakepoison

**Comment by port19x** [comment]
I should clarify why I put N to both web developer and app developer.
I see myself more as a maintainer and infrastructure person.
Writing new code isn't what I like best in such projects, but automating deployment, packaging and testing is

**Comment by dmnightshade** [comment]
Okay. I've assigned you to the app team since you are going to be working on the PossumPipe Project.
